core:
  workspace:
    DEV: "devPresentation"
    TEST: "testPresentation"
    PROD: "prodPresentation"

  workspace_id:
    DEV: "580c6ffb-f2dc-44df-950e-7b42beb79a76"
    TEST: "c69d9f07-adfe-4768-8e47-72e552e275a0"
    PROD: "173790cc-c80f-4649-afbf-23f0073ae152"

  repository_directory: "."

  item_types_in_scope:
    - Lakehouse
    - Notebook
    - DataPipeline
    - SemanticModel
    - Report
    - CopyJob
    - Dataflow
    - Warehouse
    - Environment
  
  parameter: "parameter.yml"

features:
    - enable_experimental_features
    - enable_config_deploy
    - enable_shortcut_publish
    - enable_items_to_include

constants:
    DEFAULT_API_ROOT_URL: "https://api.fabric.microsoft.com"