name: Deploy to TEST

on:
  push:
    branches: [ test ]
  # workflow_dispatch:
  #   inputs:
  #     workspaces:
  #       description: "Comma-separated: engineering,store,integration,orchestration,presentation,insights"
  #       required: true
  #       default: "engineering,store,integration"
  #     items_in_scope:
  #       description: "Comma-separated item types"
  #       required: true
  #       default: "Lakehouse,Notebook,DataPipeline,SemanticModel,Report,CopyJob,Dataflow"

env:
  AZURE_TENANT_ID:   ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID:   ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Optional: use GitHub Environments for approvals
    environment: test

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install fabric-cicd azure-identity requests ms-fabric-cli

      # - name: Azure login (service principal)
      #   shell: pwsh
      #   run: |
      #     Install-Module -Name Az.Accounts -AllowClobber -Force -Scope CurrentUser
      #     $sec = ConvertTo-SecureString "$env:AZURE_CLIENT_SECRET" -AsPlainText -Force
      #     $creds = New-Object System.Management.Automation.PSCredential ($env:AZURE_CLIENT_ID, $sec)
      #     Connect-AzAccount -ServicePrincipal -Credential $creds -Tenant $env:AZURE_TENANT_ID
      #     $token = (Get-AzAccessToken -ResourceUrl "https://api.fabric.microsoft.com").Token
      #     Write-Host "Fabric token acquired"

      - name: Deploy selected workspaces to TEST
        run: |
          IFS=',' read -ra WS_LIST <<< "${{ github.event.inputs.workspaces || 'store,engineering,integration,orchestration,presentation,insights' }}"
          ITEMS_IN_SCOPE="${{ github.event.inputs.items_in_scope || 'Lakehouse,Notebook,DataPipeline,SemanticModel,Report,CopyJob,Dataflow,Warehouse,Environment' }}"

          for ws in "${WS_LIST[@]}"; do
            case "$ws" in
                store)
                python .deploy/deploy.py \
                  --workspace-id "${{ vars.STORE_TEST_WS_ID }}" \
                  --environment TEST \
                  --repo-dir "./workspace/store" \
                  --items-in-scope "$ITEMS_IN_SCOPE"
                ;;
              engineering)
                python .deploy/deploy.py \
                  --workspace-id "${{ vars.ENGINEERING_TEST_WS_ID }}" \
                  --environment TEST \
                  --repo-dir "./workspace/engineering" \
                  --items-in-scope "$ITEMS_IN_SCOPE"
                ;;
              integration)
                python .deploy/deploy.py \
                  --workspace-id "${{ vars.INTEGRATION_TEST_WS_ID }}" \
                  --environment TEST \
                  --repo-dir "./workspace/integration" \
                  --items-in-scope "$ITEMS_IN_SCOPE"
                ;;
              orchestration)
                python .deploy/deploy.py \
                  --workspace-id "${{ vars.ORCHESTRATION_TEST_WS_ID }}" \
                  --environment TEST \
                  --repo-dir "./workspace/orchestration" \
                  --items-in-scope "$ITEMS_IN_SCOPE"
                ;;
              *)
                echo "Unknown workspace: $ws"
                ;;
            esac
          done

      - name: Show Fabric CI/CD error log
        if: failure()          # or `always()` if you want it even on success
        run: |
          echo "===== fabric_cicd.error.log ====="
          cat /home/runner/work/fabric-project/fabric-project/fabric_cicd.error.log

      - name: Run ApplyChanges to Deploy all Dataflows in integration workspace
        shell: bash
        run: |
          python .deploy/applyChanges.py \
            --tenant-id "${{ secrets.AZURE_TENANT_ID }}" \
            --client-id "${{ secrets.AZURE_CLIENT_ID }}" \
            --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --workspace-id "${{ vars.INTEGRATION_TEST_WS_ID }}" 


      - name: Login to fabric CLI using Service Principal
        run: |
          fab auth login \
            -u "${{ secrets.AZURE_CLIENT_ID }}" \
            -p "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Run pipeline responsible for hydrating storages with data.
        run: |
          fab job run testOrchestration.Workspace/pip_orchestrateDataRefresh.DataPipeline